### ISSUE TITLE
MainTools      WARNIN| error: file not found cv-valid-dev_sample-000001.gmm

### ISSUE THREAD

**Issue by gooofy** [adamcsvarga/speaker-clustering#1]
Hi,

trying to segment mozilla common voice by speaker here - copied a few sample files to wav/ and also (the same ones) to test/ (not sure if this is the right approach - I have no labeled training data whatsoever so I am not sure what goes into wav and what goes into test...) and tried ./run.sh

noticed a few warnings like:

MainTools      WARNIN| error: file not found cv-valid-dev_sample-000001.gmm

then it ultimately fails with

11:15.029 HClustering    INFO  | cross distance ( S6 , S7 ) = 2.61998110872399  {printDistance() / 1}
11:15.029 HClustering    INFO  | cross distance ( S6 , S8 ) = 2.652513280304325 {printDistance() / 1}
11:15.029 HClustering    INFO  | cross distance ( S6 , S9 ) = 2.4904591409136767        {printDistance() / 1}
11:15.029 HClustering    INFO  | cross distance ( S7 , S8 ) = 2.883782710869431 {printDistance() / 1}
11:15.029 HClustering    INFO  | cross distance ( S7 , S9 ) = 2.8115213814812985        {printDistance() / 1}
11:15.029 HClustering    INFO  | cross distance ( S8 , S9 ) = 2.7521519426254937        {printDistance() / 1}
11:15.030 ClusterSet     INFO  | --> write ClusterSet : sample/cross.seg / cross        {write() / 1}
Traceback (most recent call last):
  File "assign_clusters.py", line 32, in <module>
    assign(sys.argv[1])
  File "assign_clusters.py", line 23, in assign
    with open('data/' + dir_name + '/' + dir_name + '.c.3.seg', 'r') as binfile:
IOError: [Errno 2] No such file or directory: 'data//.c.3.seg'
Traceback (most recent call last):
  File "concat_seg.py", line 49, in <module>
    append_seg(sys.argv[1])
  File "concat_seg.py", line 32, in append_seg
    with open(segfile + '.final.seg') as source:
IOError: [Errno 2] No such file or directory: 'data/cv-valid-dev_sample-000000/cv-valid-dev_sample-000000.final.seg'

any ideas?

thanks!

   guenter

**Comment by gooofy** [comment]
I have managed to get it working - I have created my own fork where i have added missing scripts, fixed bugs and ported run.sh to python for scalability:

https://github.com/gooofy/speaker-clustering

drop me a line if you want me to create a pull request! :)

**Comment by adamcsvarga** [comment]
Hey, thanks for the fixes! Could you create a pull request?

**Comment by gooofy** [comment]
ok, done :)
